//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 11:47:46 ÉÏÎç CST 
//


package com.alibaba.courier.plugin.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.alibaba.courier.plugin.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Plugins_QNAME = new QName("http://assets.1688.com/xml/ns/plugin.xsd", "plugins");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.alibaba.courier.plugin.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PluginType }
     * 
     */
    public PluginType createPluginType() {
        return new PluginType();
    }

    /**
     * Create an instance of {@link PluginAppType }
     * 
     */
    public PluginAppType createPluginAppType() {
        return new PluginAppType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginAppType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://assets.1688.com/xml/ns/plugin.xsd", name = "plugins")
    public JAXBElement<PluginAppType> createPlugins(PluginAppType value) {
        return new JAXBElement<PluginAppType>(_Plugins_QNAME, PluginAppType.class, null, value);
    }

}
